# Generated by Django 5.0.6 on 2024-09-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='catagory',
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
